DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON usuario
FOR EACH ROW
BEGIN
DELETE FROM historico WHERE USUARIO_ID = OLD.USUARIO_ID;
DELETE FROM seguindo_artista WHERE USUARIO_ID = OLD.USUARIO_ID;
END $$
DELIMITER ;
